apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/indresh-28/templates-new.git
    targetRevision: HEAD
    path: infra/clusters/argocd-apps
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      
