project: default

source:
  repoURL: https://github.com/indresh-28/templates-new.git
  targetRevision: main
  
destination:
  server: https://kubernetes.default.svc

syncPolicy:
  CreateNamespace: true
  automated:
    prune: false
    selfHeal: true

tektonPath: cicd/tekton-pipelines
