project: default

global:
  clusterConfigPath: infra/clusters/cluster-configs

source:
  repoURL: https://github.com/indresh-28/templates-new.git
  targetRevision: main
  
destination:
  server: https://kubernetes.default.svc
  namespace: crossplane

syncPolicy:
  CreateNamespace: true
  automated:
    prune: true
    selfHeal: true

compositions:
  - name: aws-compositions
    path: infra/clusters/compositions/aws
